#!/bin/bash

# set fuses
# LOW nothing selected
avrdude \
	-v \
	-D \
	-patmega328p \
	-cusbasp \
	-Pusb \
	-U lfuse:w:0xFF:m

# HIGH = BOOTRST | BOOTSZ1 | EESAVE | SPIEN 
avrdude \
	-v \
	-D \
	-patmega328p \
	-cusbasp \
	-Pusb \
	-U hfuse:w:0xD2:m

# EXTENDED = BODLEVEL1
avrdude \
	-v \
	-D \
	-patmega328p \
	-cusbasp \
	-Pusb \
	-U efuse:w:0xFD:m

# flash
avrdude \
	-v \
	-D \
	-patmega328p \
	-cusbasp \
	-Pusb \
	-Uflash:w:../.pio/build/castellino/firmware.hex:i

echo "Success?"
